// Code generated by cervorules-policygen; DO NOT EDIT.

package policyrules

import (
	"context"
	"fmt"
	"strings"

	cervorules "github.com/cervantesh/cervo-rules/v3/core"
	cervoruntime "github.com/cervantesh/cervo-rules/v3/runtime"
	policyvocab "github.com/cervantesh/calvoproxy/internal/router/policyvocab"
)

type PolicyFactory struct{}

func NewPolicyFactory() PolicyFactory { return PolicyFactory{} }

func (PolicyFactory) Metadata() cervoruntime.PolicyMetadata {
	return cervoruntime.PolicyMetadata{
		Name:           "calvoproxy.v3",
		DSLVersion:     "cervorules.policy.v3",
		GeneratedWith:  "cervorules-policygen/v3",
		VocabularyHash: "8b062bf6de8f9e9c13afd936dafc610f4af39cc71c05116d897139c7cb205320",
		PolicyHash:     "4085fa602cf2649291b652bd93c62d1d134753da2b469383fbc0912240bde3c8",
	}
}

func (PolicyFactory) DefaultConfig() cervoruntime.PolicyRuntimeConfig {
	return cervoruntime.PolicyRuntimeConfig{
		TrustedUsers: []string{
			"cervantes",
		},
		DefaultExecutor: cervorules.Executor("openrouter"),
		OperationTargets: map[cervorules.Operation]cervorules.Target{
			cervorules.Operation("chat_completion"):    cervorules.Target("cervocore"),
			cervorules.Operation("embedding"):          cervorules.Target("cervocore"),
			cervorules.Operation("planning"):           cervorules.Target("cervocore"),
			cervorules.Operation("secret_lookup"):      cervorules.Target("cervovault_api"),
			cervorules.Operation("telegram_webhook"):   cervorules.Target("cervobridge"),
			cervorules.Operation("tool_orchestration"): cervorules.Target("cervocore"),
		},
		ExecutorFallbacks: map[cervorules.Executor][]cervorules.Executor{},
	}
}

func (PolicyFactory) ValidateConfig(cfg cervoruntime.PolicyRuntimeConfig) error {
	vocab := policyvocab.Vocabulary()
	var errs cervorules.Errors
	if cfg.DefaultExecutor != "" {
		errs = appendRuntimeValidationError(errs, vocab.ValidateExecutor(cfg.DefaultExecutor), "defaults.executor")
	}
	for operation, target := range cfg.OperationTargets {
		operationField := fmt.Sprintf("operation_targets[%s]", operation)
		errs = appendRuntimeValidationError(errs, vocab.ValidateOperation(operation), operationField)
		errs = appendRuntimeValidationError(errs, vocab.ValidateTarget(target), operationField+".target")
	}
	for executor, fallbacks := range cfg.ExecutorFallbacks {
		executorField := fmt.Sprintf("executor_fallbacks[%s]", executor)
		errs = appendRuntimeValidationError(errs, vocab.ValidateExecutor(executor), executorField)
		for i, fallback := range fallbacks {
			errs = appendRuntimeValidationError(errs, vocab.ValidateExecutor(fallback), fmt.Sprintf("%s[%d]", executorField, i))
		}
	}
	if len(errs) > 0 {
		return errs.SortStable()
	}
	return nil
}

func appendRuntimeValidationError(errs cervorules.Errors, err error, field string) cervorules.Errors {
	if err == nil {
		return errs
	}
	switch typed := err.(type) {
	case cervorules.Error:
		typed.Field = field
		return append(errs, typed)
	case cervorules.Errors:
		for _, item := range typed {
			item.Field = field
			errs = append(errs, item)
		}
		return errs
	default:
		return append(errs, cervorules.Error{Code: cervorules.ErrorCodeInvalidRuntimeConfig, Field: field, Reason: err.Error()})
	}
}

func (PolicyFactory) Build(ctx context.Context, cfg cervoruntime.PolicyRuntimeConfig) (cervorules.Engine, error) {
	select {
	case <-ctx.Done():
		return nil, ctx.Err()
	default:
	}
	factory := PolicyFactory{}
	base := factory.DefaultConfig()
	cfg = mergeRuntimeConfig(base, cfg)
	if err := factory.ValidateConfig(cfg); err != nil {
		return nil, cervoruntime.NewPolicyBuildError(factory.Metadata(), err)
	}
	routes := map[cervorules.Operation]generatedRoute{
		cervorules.Operation("chat_completion"):    {target: cervorules.Target("cervocore"), executor: cervorules.Executor(""), reason: "route matched", requiresTrustedUser: false},
		cervorules.Operation("embedding"):          {target: cervorules.Target("cervocore"), executor: cervorules.Executor(""), reason: "route matched", requiresTrustedUser: false},
		cervorules.Operation("planning"):           {target: cervorules.Target("cervocore"), executor: cervorules.Executor(""), reason: "route matched", requiresTrustedUser: false},
		cervorules.Operation("secret_lookup"):      {target: cervorules.Target("cervovault_api"), executor: cervorules.Executor(""), reason: "route matched", requiresTrustedUser: true},
		cervorules.Operation("telegram_webhook"):   {target: cervorules.Target("cervobridge"), executor: cervorules.Executor(""), reason: "route matched", requiresTrustedUser: false},
		cervorules.Operation("tool_orchestration"): {target: cervorules.Target("cervocore"), executor: cervorules.Executor(""), reason: "route matched", requiresTrustedUser: false},
	}
	disabledRoutes := map[cervorules.Operation]generatedRoute{
		cervorules.Operation("media_request"): {target: cervorules.Target("cervomedia"), executor: cervorules.Executor(""), reason: "runtime override", requiresTrustedUser: false},
	}
	trustedUsers := map[string]struct{}{}
	for _, user := range cfg.TrustedUsers {
		if normalized := strings.ToLower(strings.TrimSpace(user)); normalized != "" {
			trustedUsers[normalized] = struct{}{}
		}
	}
	for operation, target := range cfg.OperationTargets {
		route, ok := routes[operation]
		if !ok {
			route = disabledRoutes[operation]
		}
		route.target = target
		if route.executor == "" {
			route.executor = cfg.DefaultExecutor
		}
		if route.reason == "" {
			route.reason = "runtime override"
		}
		routes[operation] = route
	}
	disabledDenies := map[cervorules.Operation]string{
		cervorules.Operation("media_request"): "media backend not configured",
	}
	denies := map[cervorules.Operation]string{}
	return generatedEngine{routes: routes, denies: denies, disabledDenies: disabledDenies, trustedUsers: trustedUsers, defaultExecutor: cfg.DefaultExecutor, executorFallbacks: cfg.ExecutorFallbacks}, nil
}

func mergeRuntimeConfig(base, override cervoruntime.PolicyRuntimeConfig) cervoruntime.PolicyRuntimeConfig {
	out := base.Clone()
	if len(override.TrustedUsers) > 0 {
		out.TrustedUsers = append([]string(nil), override.TrustedUsers...)
	}
	if override.DefaultExecutor != "" {
		out.DefaultExecutor = override.DefaultExecutor
	}
	for operation, target := range override.OperationTargets {
		if out.OperationTargets == nil {
			out.OperationTargets = map[cervorules.Operation]cervorules.Target{}
		}
		out.OperationTargets[operation] = target
	}
	for executor, fallbacks := range override.ExecutorFallbacks {
		if out.ExecutorFallbacks == nil {
			out.ExecutorFallbacks = map[cervorules.Executor][]cervorules.Executor{}
		}
		out.ExecutorFallbacks[executor] = append([]cervorules.Executor(nil), fallbacks...)
	}
	return out
}

type generatedRoute struct {
	target              cervorules.Target
	executor            cervorules.Executor
	reason              string
	requiresTrustedUser bool
}

type generatedEngine struct {
	routes            map[cervorules.Operation]generatedRoute
	denies            map[cervorules.Operation]string
	disabledDenies    map[cervorules.Operation]string
	trustedUsers      map[string]struct{}
	defaultExecutor   cervorules.Executor
	executorFallbacks map[cervorules.Executor][]cervorules.Executor
}

func (e generatedEngine) Decide(ctx context.Context, req cervorules.Request) (cervorules.DecisionResult, error) {
	return e.DecideWithOptions(ctx, req, cervorules.DecisionOptions{})
}

func (e generatedEngine) DecideWithOptions(ctx context.Context, req cervorules.Request, options cervorules.DecisionOptions) (cervorules.DecisionResult, error) {
	select {
	case <-ctx.Done():
		return cervorules.DecisionResult{}, ctx.Err()
	default:
	}
	if reason, denied := e.denies[req.Operation]; denied {
		return cervorules.NewDecisionResult(req, cervorules.Decision{Allow: false, Reason: reason}, cervorules.WithTrace(options.TraceEnabled()), cervorules.WithObservation(options.ObservationEnabled())), nil
	}
	route, ok := e.routes[req.Operation]
	if !ok {
		if reason, denied := e.disabledDenies[req.Operation]; denied {
			return cervorules.NewDecisionResult(req, cervorules.Decision{Allow: false, Reason: reason}, cervorules.WithTrace(options.TraceEnabled()), cervorules.WithObservation(options.ObservationEnabled())), nil
		}
		return cervorules.NewDecisionResult(req, cervorules.Decision{Allow: false, Reason: fmt.Sprintf("no route for operation %s", req.Operation)}, cervorules.WithTrace(options.TraceEnabled()), cervorules.WithObservation(options.ObservationEnabled())), nil
	}
	if route.requiresTrustedUser && !e.isTrustedUser(req.User) {
		return cervorules.NewDecisionResult(req, cervorules.Decision{Allow: false, Reason: fmt.Sprintf("operation %s requires trusted user", req.Operation)}, cervorules.WithTrace(options.TraceEnabled()), cervorules.WithObservation(options.ObservationEnabled())), nil
	}
	executor := route.executor
	if executor == "" {
		executor = e.defaultExecutor
	}
	decision := cervorules.Decision{Allow: true, Target: route.target, Executor: executor, FallbackExecutors: append([]cervorules.Executor(nil), e.executorFallbacks[executor]...), Reason: route.reason}
	return cervorules.NewDecisionResult(req, decision, cervorules.WithTrace(options.TraceEnabled()), cervorules.WithObservation(options.ObservationEnabled())), nil
}

func (e generatedEngine) isTrustedUser(user string) bool {
	normalized := strings.ToLower(strings.TrimSpace(user))
	if normalized == "" {
		return false
	}
	_, ok := e.trustedUsers[normalized]
	return ok
}
