// Code generated by cervorules-policygen; DO NOT EDIT.

package policyrules

import (
	"context"
	"testing"

	cervorules "github.com/cervantesh/cervo-rules/v3/core"
)

func TestGeneratedPolicyFactory(t *testing.T) {
	factory := NewPolicyFactory()
	cfg := factory.DefaultConfig()
	if err := factory.ValidateConfig(cfg); err != nil {
		t.Fatalf("validate default config: %v", err)
	}
	engine, err := factory.Build(context.Background(), cfg)
	if err != nil {
		t.Fatalf("build policy: %v", err)
	}
	metadata := factory.Metadata()
	if metadata.Name == "" || metadata.DSLVersion == "" || metadata.VocabularyHash == "" || metadata.PolicyHash == "" {
		t.Fatalf("metadata incomplete: %#v", metadata)
	}
	t.Run("chat allowed", func(t *testing.T) {
		result, err := engine.Decide(context.Background(), cervorules.Request{
			ID:        "req-chat",
			User:      "guest",
			Operation: cervorules.Operation("chat_completion"),
		})
		if err != nil {
			t.Fatalf("decide: %v", err)
		}
		if result.Decision.Allow != true {
			t.Fatalf("allow mismatch: %#v", result.Decision)
		}
		if result.Decision.Target != cervorules.Target("cervocore") {
			t.Fatalf("target mismatch: %#v", result.Decision)
		}
		if result.Decision.Executor != cervorules.Executor("openrouter") {
			t.Fatalf("executor mismatch: %#v", result.Decision)
		}
	})
	t.Run("secret trusted allowed", func(t *testing.T) {
		result, err := engine.Decide(context.Background(), cervorules.Request{
			ID:        "req-secret-trusted",
			User:      "cervantes",
			Operation: cervorules.Operation("secret_lookup"),
		})
		if err != nil {
			t.Fatalf("decide: %v", err)
		}
		if result.Decision.Allow != true {
			t.Fatalf("allow mismatch: %#v", result.Decision)
		}
		if result.Decision.Target != cervorules.Target("cervovault_api") {
			t.Fatalf("target mismatch: %#v", result.Decision)
		}
		if result.Decision.Executor != cervorules.Executor("openrouter") {
			t.Fatalf("executor mismatch: %#v", result.Decision)
		}
	})
	t.Run("media denied", func(t *testing.T) {
		result, err := engine.Decide(context.Background(), cervorules.Request{
			ID:        "req-media",
			User:      "guest",
			Operation: cervorules.Operation("media_request"),
		})
		if err != nil {
			t.Fatalf("decide: %v", err)
		}
		if result.Decision.Allow != false {
			t.Fatalf("allow mismatch: %#v", result.Decision)
		}
		if result.Decision.Reason != "media backend not configured" {
			t.Fatalf("reason mismatch: %#v", result.Decision)
		}
	})
}
