// Code generated by cervorules-policygen; DO NOT EDIT.

package policyrules

import (
	"context"
	"fmt"
	"strconv"
	"strings"

	policyvocab "github.com/cervantesh/calvoproxy/internal/router/policyvocab"
	cervorules "github.com/cervantesh/cervo-rules/v3/core"
	cervoruntime "github.com/cervantesh/cervo-rules/v3/runtime"
)

type PolicyFactory struct{}

func NewPolicyFactory() PolicyFactory { return PolicyFactory{} }

func (PolicyFactory) Metadata() cervoruntime.PolicyMetadata {
	return cervoruntime.PolicyMetadata{
		Name:           "calvoproxy.v3",
		DSLVersion:     "cervorules.policy.v3",
		GeneratedWith:  "cervorules-policygen/v3",
		VocabularyHash: "323bc0e5371aa197be24d4b061a024394d35a084b2378625e3461bafaaa6a262",
		PolicyHash:     "8ae977a39b798e431067bb4a6705e78ed80bb17c4021ef2df3d60d89dec47508",
	}
}

func (PolicyFactory) DefaultConfig() cervoruntime.PolicyRuntimeConfig {
	return cervoruntime.PolicyRuntimeConfig{
		TrustedUsers: []string{
			"cervantes",
		},
		DefaultExecutor: cervorules.Executor("openrouter"),
		OperationTargets: map[cervorules.Operation]cervorules.Target{
			cervorules.Operation("chat_completion"):    cervorules.Target("cervocore"),
			cervorules.Operation("embedding"):          cervorules.Target("cervocore"),
			cervorules.Operation("planning"):           cervorules.Target("cervocore"),
			cervorules.Operation("secret_lookup"):      cervorules.Target("cervovault_api"),
			cervorules.Operation("telegram_webhook"):   cervorules.Target("cervobridge"),
			cervorules.Operation("tool_orchestration"): cervorules.Target("cervocore"),
		},
		ExecutorFallbacks: map[cervorules.Executor][]cervorules.Executor{},
	}
}

func (PolicyFactory) ValidateConfig(cfg cervoruntime.PolicyRuntimeConfig) error {
	vocab := policyvocab.Vocabulary()
	var errs cervorules.Errors
	if cfg.DefaultExecutor != "" {
		errs = appendRuntimeValidationError(errs, vocab.ValidateExecutor(cfg.DefaultExecutor), "defaults.executor")
	}
	for operation, target := range cfg.OperationTargets {
		operationField := fmt.Sprintf("operation_targets[%s]", operation)
		errs = appendRuntimeValidationError(errs, vocab.ValidateOperation(operation), operationField)
		errs = appendRuntimeValidationError(errs, vocab.ValidateTarget(target), operationField+".target")
	}
	for executor, fallbacks := range cfg.ExecutorFallbacks {
		executorField := fmt.Sprintf("executor_fallbacks[%s]", executor)
		errs = appendRuntimeValidationError(errs, vocab.ValidateExecutor(executor), executorField)
		for i, fallback := range fallbacks {
			errs = appendRuntimeValidationError(errs, vocab.ValidateExecutor(fallback), fmt.Sprintf("%s[%d]", executorField, i))
		}
	}
	if len(errs) > 0 {
		return errs.SortStable()
	}
	return nil
}

func appendRuntimeValidationError(errs cervorules.Errors, err error, field string) cervorules.Errors {
	if err == nil {
		return errs
	}
	switch typed := err.(type) {
	case cervorules.Error:
		typed.Field = field
		return append(errs, typed)
	case cervorules.Errors:
		for _, item := range typed {
			item.Field = field
			errs = append(errs, item)
		}
		return errs
	default:
		return append(errs, cervorules.Error{Code: cervorules.ErrorCodeInvalidRuntimeConfig, Field: field, Reason: err.Error()})
	}
}

func (PolicyFactory) Build(ctx context.Context, cfg cervoruntime.PolicyRuntimeConfig) (cervorules.Engine, error) {
	select {
	case <-ctx.Done():
		return nil, ctx.Err()
	default:
	}
	factory := PolicyFactory{}
	base := factory.DefaultConfig()
	cfg = mergeRuntimeConfig(base, cfg)
	if err := factory.ValidateConfig(cfg); err != nil {
		return nil, cervoruntime.NewPolicyBuildError(factory.Metadata(), err)
	}
	routes := map[cervorules.Operation]generatedRoute{
		cervorules.Operation("chat_completion"):    {target: cervorules.Target("cervocore"), executor: cervorules.Executor(""), id: "chat_completion", reason: "route matched", requiresTrustedUser: false, requires: nil, match: nil},
		cervorules.Operation("embedding"):          {target: cervorules.Target("cervocore"), executor: cervorules.Executor(""), id: "embedding", reason: "route matched", requiresTrustedUser: false, requires: nil, match: nil},
		cervorules.Operation("planning"):           {target: cervorules.Target("cervocore"), executor: cervorules.Executor(""), id: "planning", reason: "route matched", requiresTrustedUser: false, requires: nil, match: nil},
		cervorules.Operation("secret_lookup"):      {target: cervorules.Target("cervovault_api"), executor: cervorules.Executor(""), id: "secret_lookup", reason: "route matched", requiresTrustedUser: true, requires: nil, match: nil},
		cervorules.Operation("telegram_webhook"):   {target: cervorules.Target("cervobridge"), executor: cervorules.Executor(""), id: "telegram_webhook", reason: "route matched", requiresTrustedUser: false, requires: nil, match: nil},
		cervorules.Operation("tool_orchestration"): {target: cervorules.Target("cervocore"), executor: cervorules.Executor(""), id: "tool_orchestration", reason: "route matched", requiresTrustedUser: false, requires: nil, match: nil},
	}
	disabledRoutes := map[cervorules.Operation]generatedRoute{
		cervorules.Operation("media_request"): {target: cervorules.Target("cervomedia"), executor: cervorules.Executor(""), id: "media_request", reason: "runtime override", requiresTrustedUser: false, requires: nil, match: nil},
	}
	trustedUsers := map[string]struct{}{}
	for _, user := range cfg.TrustedUsers {
		if normalized := strings.ToLower(strings.TrimSpace(user)); normalized != "" {
			trustedUsers[normalized] = struct{}{}
		}
	}
	for operation, target := range cfg.OperationTargets {
		route, ok := routes[operation]
		if !ok {
			route = disabledRoutes[operation]
		}
		route.target = target
		if route.executor == "" {
			route.executor = cfg.DefaultExecutor
		}
		if route.id == "" {
			route.id = string(operation)
		}
		if route.reason == "" {
			route.reason = "runtime override"
		}
		routes[operation] = route
	}
	disabledDenies := map[cervorules.Operation]string{
		cervorules.Operation("media_request"): "media backend not configured",
	}
	denies := []generatedDeny{
		{id: "deny-oversized-body", reason: "request body exceeds the size this policy allows", requires: nil, match: matchRule0DenyOversizedBody},
	}
	return generatedEngine{routes: routes, denies: denies, disabledDenies: disabledDenies, trustedUsers: trustedUsers, defaultExecutor: cfg.DefaultExecutor, executorFallbacks: cfg.ExecutorFallbacks, conditions: cfg.Conditions}, nil
}

func mergeRuntimeConfig(base, override cervoruntime.PolicyRuntimeConfig) cervoruntime.PolicyRuntimeConfig {
	out := base.Clone()
	if len(override.TrustedUsers) > 0 {
		out.TrustedUsers = append([]string(nil), override.TrustedUsers...)
	}
	if override.DefaultExecutor != "" {
		out.DefaultExecutor = override.DefaultExecutor
	}
	// The evaluator only ever arrives from the caller: DefaultConfig cannot
	// supply one. Dropping it here made every condition-gated policy fail to
	// build, because ValidateConfig then saw no evaluator at all.
	if override.Conditions != nil {
		out.Conditions = override.Conditions
	}
	for operation, target := range override.OperationTargets {
		if out.OperationTargets == nil {
			out.OperationTargets = map[cervorules.Operation]cervorules.Target{}
		}
		out.OperationTargets[operation] = target
	}
	for executor, fallbacks := range override.ExecutorFallbacks {
		if out.ExecutorFallbacks == nil {
			out.ExecutorFallbacks = map[cervorules.Executor][]cervorules.Executor{}
		}
		out.ExecutorFallbacks[executor] = append([]cervorules.Executor(nil), fallbacks...)
	}
	return out
}

// factFrame holds the facts this policy reads, parsed once per decision.
type factFrame struct {
	factBodyBytes int64
}

// newFactFrame parses every fact this policy reads before any rule runs.
// A fact that is absent, unparseable, non-finite or outside its declared
// bounds fails the decision with a structured error. It never reports a
// predicate as unsatisfied, which would read as "the guard ran and found
// nothing wrong".
func newFactFrame(req cervorules.Request) (factFrame, error) {
	var frame factFrame
	var err error
	if frame.factBodyBytes, err = factIntegerValue(req, "body_bytes", factIntegerBounds{hasDefault: true, def: 0, hasMin: true, min: 0}); err != nil {
		return factFrame{}, err
	}
	return frame, nil
}

// factRawValue reports the trimmed metadata value for a fact. A blank value
// counts as absent: an empty string is not an answer.
func factRawValue(req cervorules.Request, name string) (string, bool) {
	raw, ok := req.Metadata[name]
	if !ok {
		return "", false
	}
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return "", false
	}
	return raw, true
}

func missingFactError(name string) error {
	return cervorules.Error{
		Code:       cervorules.ErrorCodeMissingFact,
		Severity:   cervorules.SeverityFatal,
		Component:  "policy",
		Field:      "facts." + name,
		Reason:     "fact is absent from request metadata and the policy declares no default",
		Suggestion: "supply the fact in Request.Metadata, or declare a default for it in the policy",
	}
}

// invalidFactError marks the observed value sensitive: only the caller knows
// whether a fact carries secrets, so it is withheld from serialization by
// default and still available in process.
func invalidFactError(name string, value string, reason string) error {
	return cervorules.Error{
		Code:      cervorules.ErrorCodeInvalidFact,
		Severity:  cervorules.SeverityFatal,
		Component: "policy",
		Field:     "facts." + name,
		Value:     value,
		Reason:    reason,
		Sensitive: true,
	}
}

type factIntegerBounds struct {
	hasDefault bool
	def        int64
	hasMin     bool
	min        int64
	hasMax     bool
	max        int64
}

func factIntegerValue(req cervorules.Request, name string, bounds factIntegerBounds) (int64, error) {
	raw, ok := factRawValue(req, name)
	if !ok {
		if bounds.hasDefault {
			return bounds.def, nil
		}
		return 0, missingFactError(name)
	}
	value, err := strconv.ParseInt(raw, 10, 64)
	if err != nil {
		return 0, invalidFactError(name, raw, "fact is not an integer")
	}
	if bounds.hasMin && value < bounds.min {
		return 0, invalidFactError(name, raw, "fact is below its declared minimum")
	}
	if bounds.hasMax && value > bounds.max {
		return 0, invalidFactError(name, raw, "fact is above its declared maximum")
	}
	return value, nil
}

// ruleMatcher is a compiled predicate. It reports whether the rule matched
// and which leaf decided it, so a trace step can name the reason.
type ruleMatcher func(ctx context.Context, e generatedEngine, req cervorules.Request, f factFrame) (bool, string, error)

// body_bytes gt 10485760
func matchRule0DenyOversizedBody(ctx context.Context, e generatedEngine, req cervorules.Request, f factFrame) (bool, string, error) {
	if f.factBodyBytes > 10485760 {
		return true, "body_bytes gt 10485760", nil
	}
	return false, "", nil
}

type generatedRoute struct {
	target   cervorules.Target
	executor cervorules.Executor
	// id names the rule in a trace step; reason is what the decision carries.
	id                  string
	reason              string
	requiresTrustedUser bool
	requires            []cervorules.Condition
	match               ruleMatcher
}

// generatedDeny is one ordered deny rule. An empty operation applies it to
// every operation.
type generatedDeny struct {
	operation cervorules.Operation
	id        string
	reason    string
	requires  []cervorules.Condition
	match     ruleMatcher
}

type generatedEngine struct {
	routes            map[cervorules.Operation]generatedRoute
	denies            []generatedDeny
	disabledDenies    map[cervorules.Operation]string
	trustedUsers      map[string]struct{}
	defaultExecutor   cervorules.Executor
	executorFallbacks map[cervorules.Executor][]cervorules.Executor
	conditions        cervorules.Conditions
}

func (e generatedEngine) Decide(ctx context.Context, req cervorules.Request) (cervorules.DecisionResult, error) {
	return e.DecideWithOptions(ctx, req, cervorules.DecisionOptions{})
}

func (e generatedEngine) DecideWithOptions(ctx context.Context, req cervorules.Request, options cervorules.DecisionOptions) (cervorules.DecisionResult, error) {
	select {
	case <-ctx.Done():
		return cervorules.DecisionResult{}, ctx.Err()
	default:
	}
	traceEnabled := options.TraceEnabled()
	var steps []cervorules.DecisionTraceStep
	// The frame is built before any rule runs, so a malformed fact cannot
	// hide behind an earlier rule that happened to match first.
	frame, err := newFactFrame(req)
	if err != nil {
		return cervorules.DecisionResult{}, err
	}
	for _, deny := range e.denies {
		if deny.operation != "" && deny.operation != req.Operation {
			continue
		}
		applies, err := e.conditionsHold(ctx, deny.requires, req)
		if err != nil {
			return cervorules.DecisionResult{}, err
		}
		detail := ""
		if applies && deny.match != nil {
			applies, detail, err = deny.match(ctx, e, req, frame)
			if err != nil {
				return cervorules.DecisionResult{}, err
			}
		}
		if traceEnabled {
			steps = append(steps, cervorules.DecisionTraceStep{Name: deny.id, Matched: applies, Reason: detail})
		}
		if applies {
			return e.finish(req, cervorules.Decision{Allow: false, Reason: deny.reason}, options, steps), nil
		}
	}
	route, ok := e.routes[req.Operation]
	if !ok {
		if reason, denied := e.disabledDenies[req.Operation]; denied {
			return e.finish(req, cervorules.Decision{Allow: false, Reason: reason}, options, steps), nil
		}
		return e.finish(req, cervorules.Decision{Allow: false, Reason: fmt.Sprintf("no route for operation %s", req.Operation)}, options, steps), nil
	}
	if route.requiresTrustedUser && !e.isTrustedUser(req.User) {
		return e.finish(req, cervorules.Decision{Allow: false, Reason: fmt.Sprintf("operation %s requires trusted user", req.Operation)}, options, steps), nil
	}
	eligible, err := e.conditionsHold(ctx, route.requires, req)
	if err != nil {
		return cervorules.DecisionResult{}, err
	}
	routeDetail := ""
	if eligible && route.match != nil {
		eligible, routeDetail, err = route.match(ctx, e, req, frame)
		if err != nil {
			return cervorules.DecisionResult{}, err
		}
	}
	if traceEnabled {
		steps = append(steps, cervorules.DecisionTraceStep{Name: route.id, Matched: eligible, Reason: routeDetail})
	}
	if !eligible {
		return e.finish(req, cervorules.Decision{Allow: false, Reason: fmt.Sprintf("operation %s did not satisfy its required conditions", req.Operation)}, options, steps), nil
	}
	executor := route.executor
	if executor == "" {
		executor = e.defaultExecutor
	}
	decision := cervorules.Decision{Allow: true, Target: route.target, Executor: executor, FallbackExecutors: append([]cervorules.Executor(nil), e.executorFallbacks[executor]...), Reason: route.reason}
	return e.finish(req, decision, options, steps), nil
}

// finish assembles the decision envelope and attaches the trace steps that
// were collected. Steps are only collected when trace is enabled, so an
// untraced decision allocates nothing for explanation.
func (e generatedEngine) finish(req cervorules.Request, decision cervorules.Decision, options cervorules.DecisionOptions, steps []cervorules.DecisionTraceStep) cervorules.DecisionResult {
	result := cervorules.NewDecisionResult(req, decision, cervorules.WithTrace(options.TraceEnabled()), cervorules.WithObservation(options.ObservationEnabled()))
	if result.Trace != nil {
		result.Trace.Steps = steps
	}
	return result
}

// conditionsHold reports whether every required condition holds.
// A condition that cannot be answered fails the decision instead of being
// treated as a non-match, so an unanswerable guard never silently passes.
func (e generatedEngine) conditionsHold(ctx context.Context, required []cervorules.Condition, req cervorules.Request) (bool, error) {
	if len(required) == 0 {
		return true, nil
	}
	if e.conditions == nil {
		return false, cervorules.Error{Code: cervorules.ErrorCodeMissingConditions, Severity: cervorules.SeverityFatal, Component: "policy", Field: "conditions", Reason: "policy requires conditions but no evaluator is configured"}
	}
	for _, condition := range required {
		holds, err := e.conditions.Holds(ctx, condition, req)
		if err != nil {
			return false, err
		}
		if !holds {
			return false, nil
		}
	}
	return true, nil
}

func (e generatedEngine) isTrustedUser(user string) bool {
	normalized := strings.ToLower(strings.TrimSpace(user))
	if normalized == "" {
		return false
	}
	_, ok := e.trustedUsers[normalized]
	return ok
}
