// Code generated by cervorules-vocabgen; DO NOT EDIT.

package policyvocab

import cervorules "github.com/cervantesh/cervo-rules/v3/core"

const (
	OperationChatCompletion    cervorules.Operation = "chat_completion"
	OperationEmbedding         cervorules.Operation = "embedding"
	OperationMediaRequest      cervorules.Operation = "media_request"
	OperationPlanning          cervorules.Operation = "planning"
	OperationSecretLookup      cervorules.Operation = "secret_lookup"
	OperationTelegramWebhook   cervorules.Operation = "telegram_webhook"
	OperationToolOrchestration cervorules.Operation = "tool_orchestration"
)

const (
	TargetCervoBridge   cervorules.Target = "cervobridge"
	TargetCervoCore     cervorules.Target = "cervocore"
	TargetCervoMedia    cervorules.Target = "cervomedia"
	TargetCervoVaultAPI cervorules.Target = "cervovault_api"
	TargetCrashitoBrain cervorules.Target = "crashito_brain"
)

const (
	ExecutorAnthropic  cervorules.Executor = "anthropic"
	ExecutorLocal      cervorules.Executor = "local"
	ExecutorOllama     cervorules.Executor = "ollama"
	ExecutorOpenAI     cervorules.Executor = "openai"
	ExecutorOpenRouter cervorules.Executor = "openrouter"
)

const (
	FactBodyBytes = "body_bytes"
)

func Vocabulary() cervorules.Vocabulary {
	return cervorules.NewVocabulary(
		cervorules.AllowedOperations(
			OperationChatCompletion,
			OperationEmbedding,
			OperationMediaRequest,
			OperationPlanning,
			OperationSecretLookup,
			OperationTelegramWebhook,
			OperationToolOrchestration,
		),
		cervorules.AllowedTargets(
			TargetCervoBridge,
			TargetCervoCore,
			TargetCervoMedia,
			TargetCervoVaultAPI,
			TargetCrashitoBrain,
		),
		cervorules.AllowedExecutors(
			ExecutorAnthropic,
			ExecutorLocal,
			ExecutorOllama,
			ExecutorOpenAI,
			ExecutorOpenRouter,
		),
	)
}
