#!/usr/bin/env bash
# Coverage ratchet.
#
# This repo publishes fast — 20 releases in about 30 hours at one point — and
# that is a deliberate choice. The risk it carries is that coverage erodes one
# hurried PR at a time and nobody notices until a regression ships. This gate
# makes the erosion loud: floors only ever move UP, and the numbers live in
# coverage-floors.txt where raising them is a visible line in a diff.
#
# Floors are set at the CURRENT measured value, not at an aspiration. A failure
# means this change removed coverage that existed before it — not that the repo
# fell short of some ideal.
#
#   ./scripts/coverage-gate.sh          # check
#   ./scripts/coverage-gate.sh --update # rewrite floors to today's numbers
set -euo pipefail

cd "$(dirname "$0")/.."
FLOORS="scripts/coverage-floors.txt"
PROFILE="${COVERAGE_PROFILE:-coverage.out}"
# Only packages that carry tests. ./... would also pull in tools/ and test/load/,
# which have no tests to measure and only add noise (and, on a machine with two
# Go installs on PATH, a toolchain-mismatch failure that has nothing to do with
# coverage).
PKGS="${COVERAGE_PKGS:-./internal/... ./cmd/...}"

# shellcheck disable=SC2086
go test $PKGS -coverprofile="$PROFILE" >/dev/null

measured=$(mktemp)
trap 'rm -f "$measured"' EXIT

# Per-package totals.
# shellcheck disable=SC2086
go test $PKGS -cover 2>/dev/null \
  | awk '$1 == "ok" && /coverage: [0-9.]+% of statements/ {
      for (i = 1; i <= NF; i++) if ($i == "coverage:") { gsub(/%/, "", $(i+1)); print "pkg " $2 " " $(i+1) }
    }' >> "$measured"

# Named critical-path functions. A package total can stay flat while the
# function every request passes through loses its tests, so these are pinned by
# name rather than trusted to the average.
go tool cover -func="$PROFILE" \
  | awk '$1 != "total:" { gsub(/%/, "", $NF); split($1, p, ":"); print "func " $2 " " $NF }' \
  | sort -u >> "$measured"

if [[ "${1:-}" == "--update" ]]; then
  {
    echo "# Coverage floors — generated by scripts/coverage-gate.sh --update."
    echo "# Floors only move up. Lowering one is a deliberate, reviewable act."
    grep '^pkg ' "$measured" | sort
    # Only the critical path is pinned per-function; pinning everything would
    # turn every refactor into a floors-file edit and train people to ignore it.
    grep -E '^func (RouteRequestWithProvider|RouteRequest|dispatchChain|executeAttempt|streamProxyResponse|streamCopy|awaitFirstStreamEvent|setServedModelHeaders|planModelAttempts|applyCapabilityFilter|filterAvailableAttempts|rankAttemptsByScore) ' "$measured" | sort
  } > "$FLOORS"
  echo "floors written to $FLOORS"
  exit 0
fi

if [[ ! -f "$FLOORS" ]]; then
  echo "no $FLOORS; run: ./scripts/coverage-gate.sh --update" >&2
  exit 1
fi

fail=0
while read -r kind name floor; do
  [[ -z "${kind:-}" || "$kind" == \#* ]] && continue
  now=$(awk -v k="$kind" -v n="$name" '$1 == k && $2 == n { print $3; exit }' "$measured")
  if [[ -z "$now" ]]; then
    echo "GONE  $kind $name — floor $floor%, but it no longer reports coverage."
    echo "      If it was renamed or removed on purpose, update $FLOORS in this PR."
    fail=1
    continue
  fi
  if awk -v a="$now" -v b="$floor" 'BEGIN { exit !(a + 0.05 < b) }'; then
    echo "DROP  $kind $name: $now% < floor $floor%"
    fail=1
  fi
done < "$FLOORS"

if [[ $fail -ne 0 ]]; then
  cat >&2 <<'MSG'

Coverage went down. Add the tests, or — if the drop is correct (code deleted,
function renamed) — run ./scripts/coverage-gate.sh --update and let the changed
floors show up in the diff, where a reviewer can see them.
MSG
  exit 1
fi

echo "coverage gate: OK"
