#!/usr/bin/env bash
# Coverage ratchet.
#
# This repo publishes fast — 20 releases in about 30 hours at one point — and
# that is a deliberate choice. The risk it carries is that coverage erodes one
# hurried PR at a time and nobody notices until a regression ships. This gate
# makes the erosion loud: floors only ever move UP, and the numbers live in
# coverage-floors.txt where raising them is a visible line in a diff.
#
# Floors are set at the CURRENT measured value, not at an aspiration. A failure
# means this change removed coverage that existed before it — not that the repo
# fell short of some ideal.
#
#   ./scripts/coverage-gate.sh                          # check
#   ./scripts/coverage-gate.sh --update                 # raise floors to today
#   ./scripts/coverage-gate.sh --update --allow-lower   # ... and let floors DROP
#   ./scripts/coverage-gate.sh --update --allow-remove  # ... and let entries vanish
#
# --update on its own can only RAISE. Lowering or removing a floor needs an
# explicit flag, because the easy way to defeat a ratchet is not to argue with
# it -- it is to regenerate it in the same PR and let the numbers slide past as
# noise. The flags force that to be a deliberate act with a name on it.
set -euo pipefail

cd "$(dirname "$0")/.."
FLOORS="scripts/coverage-floors.txt"
PROFILE="${COVERAGE_PROFILE:-coverage.out}"
# Only packages that carry tests. ./... would also pull in tools/ and test/load/,
# which have no tests to measure and only add noise (and, on a machine with two
# Go installs on PATH, a toolchain-mismatch failure that has nothing to do with
# coverage).
PKGS="${COVERAGE_PKGS:-./internal/... ./cmd/...}"

# shellcheck disable=SC2086
go test $PKGS -coverprofile="$PROFILE" >/dev/null

measured=$(mktemp)
trap 'rm -f "$measured"' EXIT

# Per-package totals.
# shellcheck disable=SC2086
go test $PKGS -cover 2>/dev/null \
  | awk '$1 == "ok" && /coverage: [0-9.]+% of statements/ {
      for (i = 1; i <= NF; i++) if ($i == "coverage:") { gsub(/%/, "", $(i+1)); print "pkg " $2 " " $(i+1) }
    }' >> "$measured"

# Named critical-path functions. A package total can stay flat while the
# function every request passes through loses its tests, so these are pinned by
# name rather than trusted to the average.
go tool cover -func="$PROFILE" \
  | awk '$1 != "total:" { gsub(/%/, "", $NF); split($1, p, ":"); print "func " $2 " " $NF }' \
  | sort -u >> "$measured"

ALLOW_LOWER=0
ALLOW_REMOVE=0
UPDATE=0
for arg in "$@"; do
  case "$arg" in
    --update)       UPDATE=1 ;;
    --allow-lower)  ALLOW_LOWER=1 ;;
    --allow-remove) ALLOW_REMOVE=1 ;;
    *) echo "unknown flag: $arg" >&2; exit 2 ;;
  esac
done

# Only the critical path is pinned per-function. Pinning everything would turn
# every refactor into a floors-file edit and train people to ignore the file.
CRITICAL='^func (RouteRequestWithProvider|RouteRequest|dispatchChain|executeAttempt|streamProxyResponse|streamCopy|awaitFirstStreamEvent|setServedModelHeaders|planModelAttempts|applyCapabilityFilter|filterAvailableAttempts|rankAttemptsByScore) '

if [[ $UPDATE -eq 1 ]]; then
  proposed=$(mktemp)
  trap 'rm -f "$measured" "$proposed"' EXIT
  { grep '^pkg ' "$measured" | sort; grep -E "$CRITICAL" "$measured" | sort; } > "$proposed"

  refused=0
  if [[ -f "$FLOORS" ]]; then
    while read -r kind name floor; do
      [[ -z "${kind:-}" || "$kind" == \#* ]] && continue
      now=$(awk -v k="$kind" -v n="$name" '$1 == k && $2 == n { print $3; exit }' "$proposed")
      if [[ -z "$now" ]]; then
        if [[ $ALLOW_REMOVE -eq 0 ]]; then
          echo "REFUSING to drop the floor for $kind $name (was $floor%)." >&2
          echo "  It no longer reports coverage. If that is correct, pass --allow-remove." >&2
          refused=1
        fi
        continue
      fi
      if awk -v a="$now" -v b="$floor" 'BEGIN { exit !(a + 0.001 < b) }' && [[ $ALLOW_LOWER -eq 0 ]]; then
        echo "REFUSING to lower $kind $name: $floor% -> $now%. Pass --allow-lower if intended." >&2
        refused=1
      fi
    done < "$FLOORS"
  fi
  if [[ $refused -ne 0 ]]; then
    echo "" >&2
    echo "Nothing written. A ratchet that regenerates downward is not a ratchet." >&2
    exit 1
  fi

  {
    echo "# Coverage floors — generated by scripts/coverage-gate.sh --update."
    echo "# --update can only RAISE these. Lowering needs --allow-lower and removing"
    echo "# needs --allow-remove, so either one shows up as an argued change."
    cat "$proposed"
  } > "$FLOORS"
  echo "floors written to $FLOORS"
  exit 0
fi

if [[ ! -f "$FLOORS" ]]; then
  echo "no $FLOORS; run: ./scripts/coverage-gate.sh --update" >&2
  exit 1
fi

fail=0
while read -r kind name floor; do
  [[ -z "${kind:-}" || "$kind" == \#* ]] && continue
  now=$(awk -v k="$kind" -v n="$name" '$1 == k && $2 == n { print $3; exit }' "$measured")
  if [[ -z "$now" ]]; then
    echo "GONE  $kind $name — floor $floor%, but it no longer reports coverage."
    echo "      If it was renamed or removed on purpose, update $FLOORS in this PR."
    fail=1
    continue
  fi
  # 0.001, not a slack budget: coverage reports one decimal, so this absorbs
  # float representation only. The 0.05 this replaced quietly allowed real drops.
  if awk -v a="$now" -v b="$floor" 'BEGIN { exit !(a + 0.001 < b) }'; then
    echo "DROP  $kind $name: $now% < floor $floor%"
    fail=1
  fi
done < "$FLOORS"

if [[ $fail -ne 0 ]]; then
  cat >&2 <<'MSG'

Coverage went down. Add the tests, or — if the drop is correct (code deleted,
function renamed) — run ./scripts/coverage-gate.sh --update and let the changed
floors show up in the diff, where a reviewer can see them.
MSG
  exit 1
fi

echo "coverage gate: OK"
