#!/usr/bin/env bash
# Checksum manifest for the vendored cervo-* modules.
#
# WHY THIS EXISTS
#
# go.sum pins every dependency in this repo except these. The cervo-* modules
# are declared in go.mod with `replace ... => ./third_party/<mod>`, and
# third_party/ IS NOT IN THIS REPOSITORY. The build only works because Go
# auto-selects -mod=vendor when vendor/modules.txt is present; `go mod verify`
# fails outright, and `go mod vendor` cannot regenerate the tree.
#
# Consequences, stated plainly:
#   - There is no upstream to diff against, and no checksum database backing
#     these files. vendor/ is the only copy that exists.
#   - Nothing else would notice if their contents changed. This proxy handles
#     API keys and every request body; silent drift there is the kind of thing
#     that should be loud.
#
# This manifest is the substitute: a SHA-256 per file, checked in CI. It does
# not establish provenance — it cannot, there is no source to establish it
# against. It establishes only that the code has not changed since it was
# recorded, and forces any change to appear as a reviewable diff.
#
#   ./scripts/vendor-manifest.sh          # verify
#   ./scripts/vendor-manifest.sh --update # re-record (review the diff!)
set -euo pipefail

cd "$(dirname "$0")/.."
MANIFEST="scripts/vendor-manifest.sha256"
ROOT="vendor/github.com/cervantesh"

if [[ ! -d "$ROOT" ]]; then
  echo "no $ROOT — nothing to verify" >&2
  exit 1
fi

generate() {
  # Every regular file, no extension filter. An earlier version listed
  # *.go/*.json/*.yaml, which would have gone blind the day one of these modules
  # gained a //go:embed asset, a .s file, or a cgo source -- each of which
  # changes the built binary while looking like nothing to a filter.
  find "$ROOT" -type f \
    | LC_ALL=C sort \
    | while read -r f; do
        printf '%s  %s\n' "$(sha256sum "$f" | cut -d' ' -f1)" "$f"
      done
}

if [[ "${1:-}" == "--update" ]]; then
  {
    echo "# SHA-256 of every vendored cervo-* source file."
    echo "# Generated by scripts/vendor-manifest.sh --update."
    echo "# These modules have no go.sum entries and no reachable upstream;"
    echo "# this file is the only thing that makes a change to them visible."
    generate
  } > "$MANIFEST"
  echo "wrote $MANIFEST ($(grep -cv '^#' "$MANIFEST") files)"
  exit 0
fi

if [[ ! -f "$MANIFEST" ]]; then
  echo "no $MANIFEST; run: ./scripts/vendor-manifest.sh --update" >&2
  exit 1
fi

current=$(mktemp)
recorded=$(mktemp)
trap 'rm -f "$current" "$recorded"' EXIT

generate > "$current"
grep -v '^#' "$MANIFEST" > "$recorded"

if diff -u "$recorded" "$current" > /dev/null; then
  echo "vendored cervo-* modules: unchanged ($(wc -l < "$current" | tr -d ' ') files)"
  exit 0
fi

echo "Vendored cervo-* modules CHANGED:" >&2
diff -u "$recorded" "$current" | grep -E '^[+-][^+-]' >&2 || true
cat >&2 <<'MSG'

These modules have no go.sum entries and no reachable upstream, so this manifest
is the only check on them. If the change is intentional, run
./scripts/vendor-manifest.sh --update in the same PR so a reviewer sees exactly
which vendored files moved and why.
MSG
exit 1
