#!/usr/bin/env bash
# Checksum manifest for every vendored dependency.
#
# WHY THIS EXISTS
#
# go.sum pins every dependency in this repo except the locally replaced
# cervo-* modules. Those are declared in go.mod with
# `replace ... => ./third_party/<mod>`, and third_party/ IS NOT IN THIS
# REPOSITORY. (The public cervo-compress module is checksummed normally but is
# included in this manifest because it shares the vendored namespace.) The build
# works offline because Go
# auto-selects -mod=vendor when vendor/modules.txt is present; `go mod verify`
# fails outright, and `go mod vendor` cannot regenerate the tree.
#
# Consequences, stated plainly:
#   - There is no upstream to diff against, and no checksum database backing
#     these files. vendor/ is the only copy that exists.
#   - Nothing else would notice if their contents changed. This proxy handles
#     API keys and every request body; silent drift there is the kind of thing
#     that should be loud.
#
# This manifest is the substitute: a SHA-256 per file, checked in CI. It does
# not establish provenance — it cannot, there is no source to establish it
# against. It establishes only that the code has not changed since it was
# recorded, and forces any change to appear as a reviewable diff.
#
#   ./scripts/vendor-manifest.sh          # verify
#   ./scripts/vendor-manifest.sh --update # re-record (review the diff!)
set -euo pipefail

cd "$(dirname "$0")/.."
MANIFEST="scripts/vendor-manifest.sha256"
ROOT="vendor"

if [[ ! -d "$ROOT" ]]; then
  echo "no $ROOT — nothing to verify" >&2
  exit 1
fi

# Hash the content GIT holds, not the bytes on this disk.
#
# The working tree is not authoritative: with core.autocrlf=true (the Windows
# default) every one of these files is CRLF locally and LF on a Linux CI runner,
# so a disk-based hash reports all 54 files as modified on every push. That is
# not a hypothetical -- it is what the first CI run of this script did.
#
# `git show :path` reads the index, which holds the canonical normalized content
# that will actually be committed. Same answer on every platform and every git
# config. The .gitattributes `vendor/** -text` rule keeps the checkout
# byte-exact as well, but the manifest no longer depends on that being honoured.
#
# The trade-off, stated: this verifies what is staged/committed, not unstaged
# edits in your working tree. The manifest guards what enters the repository.
generate() {
  # Hash the INDEX content (git show ":$f"), never the file on disk. A checkout
  # on Windows rewrites vendored text to CRLF, so hashing the working tree makes
  # the manifest disagree with itself across platforms: generated on Windows it
  # fails in Linux CI for every text file at once, which reads as mass tampering
  # and hides a real one. The index is the same bytes everywhere.
  # Serial by default. Concurrent `git show` invocations were measured failing
  # sporadically on Windows, and a failed hash must never become a blank entry
  # that looks like a legitimate manifest line: an integrity check that degrades
  # quietly is worse than a slow one. VENDOR_MANIFEST_JOBS raises the batch
  # count where forks are cheap; any empty hash aborts the run either way.
  git ls-files -z "$ROOT" |
    xargs -0 -P "${VENDOR_MANIFEST_JOBS:-1}" -n 32 bash -c '
      set -euo pipefail
      for f in "$@"; do
        sum="$(git show ":$f" | sha256sum | cut -d" " -f1)"
        if [[ -z "$sum" || "${#sum}" -ne 64 ]]; then
          echo "vendor-manifest: could not hash $f" >&2
          exit 1
        fi
        printf "%s  %s\n" "$sum" "$f"
      done
    ' _ |
    LC_ALL=C sort
}

if [[ "${1:-}" == "--update" ]]; then
  {
    echo "# SHA-256 of every tracked vendored dependency file."
    echo "# Generated by scripts/vendor-manifest.sh --update."
    echo "# Locally replaced modules have no go.sum or reachable upstream;"
    echo "# public cervo-compress is included for complete vendored integrity."
    generate
  } > "$MANIFEST"
  echo "wrote $MANIFEST ($(grep -cv '^#' "$MANIFEST") files)"
  exit 0
fi

if [[ ! -f "$MANIFEST" ]]; then
  echo "no $MANIFEST; run: ./scripts/vendor-manifest.sh --update" >&2
  exit 1
fi

current=$(mktemp)
recorded=$(mktemp)
trap 'rm -f "$current" "$recorded"' EXIT

generate > "$current"
grep -v '^#' "$MANIFEST" > "$recorded"

if diff -u "$recorded" "$current" > /dev/null; then
  echo "vendored dependencies: unchanged ($(wc -l < "$current" | tr -d ' ') files)"
  exit 0
fi

echo "Vendored cervo-* modules CHANGED:" >&2
diff -u "$recorded" "$current" | grep -E '^[+-][^+-]' >&2 || true
cat >&2 <<'MSG'

Locally replaced modules have no go.sum entries or reachable upstream, so this
manifest is their only integrity check. If the change is intentional, run
./scripts/vendor-manifest.sh --update in the same PR so a reviewer sees exactly
which vendored files moved and why.
MSG
exit 1
